flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- async-2.1.1
- constraints-0.8
- enclosed-exceptions-1.0.2
- exceptions-0.8.3
- hashable-1.2.4.0
- lifted-async-0.9.0
- lifted-base-0.2.3.8
- monad-control-1.0.1.0
- mtl-2.2.1
- shelly-1.6.8.1
- split-0.2.3.1
- stm-2.4.4.1
- system-fileio-0.3.16.3
- system-filepath-0.4.13.4
- text-1.2.2.1
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.3.1
resolver: lts-6.27
